message:
    opened:
        header: "Hello @{name}, Thank you for submitting the Pull Request!"
        footer: "Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)"
    updated:
        header: "Hello @{name}, Thank you for updating!"
        footer: "Do see the ReFrame [Coding Style Guide](https://github.com/eth-cscs/reframe/wiki/coding-style-guide)"
    no_errors: "Cheers! There are no PEP8 issues in this Pull Request!"

only_mention_files_with_errors: True

scanner:
    diff_only: True

pycodestyle:
    max-line-length: 79
    ignore:
        - E129
        - E221
        - E226
        - E241
        - E272
        - E741
        - E742
        - E743
        - W504
